version: "3.8"

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile.flask
    environment:
      FLASK_APP: "app"
      FLASK_DEBUG: "true"
      FLASK_RUN_PORT: "8000"
      DATABASE_URL: "sqlite:///dev.db"
      SCHEMA: "right_track_aba_schema"
      SECRET_KEY: "lkasjdf09ajsdkfljalsiorj12n3490re9485309irefvn,u90818734902139489230"
    ports:
      - "8000:8000"
    depends_on:
      - react

  react:
    build:
      context: .
      dockerfile: Dockerfile.react
    environment:
      - BROWSER=none
    ports:
      - "5173:5173"

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - flask
  #     - react
