FROM python:3.9.18-alpine3.18

RUN apk add build-base

RUN apk add postgresql-dev gcc python3-dev musl-dev

ARG FLASK_APP
ARG FLASK_DEBUG
ARG DATABASE_URL
ARG SCHEMA
ARG SECRET_KEY

WORKDIR /var/www

COPY requirements.txt .

RUN pip install -r requirements.txt
RUN pip install psycopg2

COPY . .

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "app:app"]

# RUN flask db downgrade
# RUN flask db upgrade
# RUN flask seed all