export const behaviors = [
  "Tantrums",
  "Throwing",
  "Self-Injurious Behiavior",
  "Biting",
  "Aggression",
  "Crying",
  "Vocal Stereotypy",
  "Property Destruction",
  "Kicking",
  "Spitting",
  "Non-Compliance",
  "Elopement",
  "Task Refusal",
  "Outbursts",
  "Mouthing",
  "Negative Statements",
  "Inappropriate Language",
  "Hitting",
  "PICA",
  "Food Refusal",
];

export const activities = [
  "Reading",
  "Writing",
  "Math",
  "Science",
  "Recess",
  "Free Time",
  "Circle Time",
  "Clean Up",
  "Art",
  "Lunch",
  "Snack",
  "P.E.",
];
