client_a_data = [
    {
        "id": 1,
        "start_interval": "08:00:00",
        "end_interval": "08:15:00",
        "client_id": 1,
        "chart_id": 1,
        "activity": "Math",
        "interval_tags": {"Inattention": 5},
        "interval_rating": 2,
        "interval_notes": "Difficulty focusing, seeking attention from peers",
    },
    {
        "id": 2,
        "start_interval": "08:15:00",
        "end_interval": "08:30:00",
        "client_id": 1,
        "chart_id": 1,
        "activity": "Recess",
        "interval_tags": {"Non-Compliance": 3},
        "interval_rating": 3,
        "interval_notes": "Refused to participate in organized game",
    },
    {
        "id": 3,
        "start_interval": "08:30:00",
        "end_interval": "08:45:00",
        "client_id": 1,
        "chart_id": 1,
        "activity": "Art",
        "interval_tags": {"Task Refusal": 4, "Elopement": 1},
        "interval_rating": 1,
        "interval_notes": "Refused to start art project, seeking escape from activity",
    },
    {
        "id": 4,
        "start_interval": "08:45:00",
        "end_interval": "09:00:00",
        "chart_id": 1,
        "client_id": 1,
        "activity": "Circle Time",
        "interval_tags": {"Outbursts": 3},
        "interval_rating": 1,
        "interval_notes": "Disrupted circle time with loud outburst",
    },
    {
        "id": 5,
        "start_interval": "09:00:00",
        "end_interval": "09:15:00",
        "chart_id": 1,
        "client_id": 1,
        "activity": "Science",
        "interval_tags": {"Task Refusal": 5},
        "interval_rating": 1,
        "interval_notes": "Refused to participate in science experiment",
    },
    {
        "id": 6,
        "start_interval": "09:15:00",
        "end_interval": "09:30:00",
        "chart_id": 1,
        "client_id": 1,
        "activity": "P.E.",
        "interval_tags": {"Non-Compliance": 4},
        "interval_rating": 1,
        "interval_notes": "Ignored teacher's instructions during physical activity",
    },
    {
        "id": 7,
        "start_interval": "09:30:00",
        "end_interval": "09:45:00",
        "chart_id": 1,
        "client_id": 1,
        "activity": "Reading",
        "interval_tags": {"Inattention": 4},
        "interval_rating": 3,
        "interval_notes": "Distracted during reading, seeking attention from teacher",
    },
    {
        "id": 8,
        "start_interval": "09:45:00",
        "end_interval": "10:00:00",
        "chart_id": 1,
        "client_id": 1,
        "activity": "Lunch",
        "interval_tags": {"Non-Compliance": 5, "Throwing": 2},
        "interval_rating": 1,
        "interval_notes": "Refused to eat lunch, seeking attention from classmates",
    },
    {
        "id": 9,
        "start_interval": "10:00:00",
        "end_interval": "10:15:00",
        "chart_id": 1,
        "client_id": 1,
        "activity": "Snack",
        "interval_tags": {"Task Refusal": 3},
        "interval_rating": 3,
        "interval_notes": "Refused snack, seeking escape from activity",
    },
    {
        "id": 10,
        "start_interval": "10:15:00",
        "end_interval": "10:30:00",
        "chart_id": 1,
        "client_id": 1,
        "activity": "Music",
        "interval_tags": {"Inattention": 4, "Outbursts": 3},
        "interval_rating": 2,
        "interval_notes": "Distracted during music lesson, seeking attention",
    }]



Interval_Data = [
    {
        "id": 1,
        "start_interval": "08:00:00",
        "end_interval": "08:15:00",
        "client_id": 1,
        "chart_id": 1,
        "activity": "Math",
        "interval_tags": {"Inattention": 5},
        "interval_rating": 2,
        "interval_notes": "Difficulty focusing, seeking attention from peers",
    },
    {
        "id": 2,
        "start_interval": "08:15:00",
        "end_interval": "08:30:00",
        "client_id": 1,
        "chart_id": 1,
        "activity": "Recess",
        "interval_tags": {"Non-Compliance": 3},
        "interval_rating": 3,
        "interval_notes": "Refused to participate in organized game",
    },
    {
        "id": 3,
        "start_interval": "08:30:00",
        "end_interval": "08:45:00",
        "client_id": 1,
        "chart_id": 1,
        "activity": "Art",
        "interval_tags": {"Task Refusal": 4, "Elopement": 1},
        "interval_rating": 1,
        "interval_notes": "Refused to start art project, seeking escape from activity",
    },
    {
        "id": 4,
        "start_interval": "08:45:00",
        "end_interval": "09:00:00",
        "chart_id": 1,
        "client_id": 1,
        "activity": "Circle Time",
        "interval_tags": {"Outbursts": 3},
        "interval_rating": 1,
        "interval_notes": "Disrupted circle time with loud outburst",
    },
    {
        "id": 5,
        "start_interval": "09:00:00",
        "end_interval": "09:15:00",
        "chart_id": 1,
        "client_id": 1,
        "activity": "Science",
        "interval_tags": {"Task Refusal": 5},
        "interval_rating": 1,
        "interval_notes": "Refused to participate in science experiment",
    },
    {
        "id": 6,
        "start_interval": "09:15:00",
        "end_interval": "09:30:00",
        "chart_id": 1,
        "client_id": 1,
        "activity": "P.E.",
        "interval_tags": {"Non-Compliance": 4},
        "interval_rating": 1,
        "interval_notes": "Ignored teacher's instructions during physical activity",
    },
    {
        "id": 7,
        "start_interval": "09:30:00",
        "end_interval": "09:45:00",
        "chart_id": 1,
        "client_id": 1,
        "activity": "Reading",
        "interval_tags": {"Inattention": 4},
        "interval_rating": 3,
        "interval_notes": "Distracted during reading, seeking attention from teacher",
    },
    {
        "id": 8,
        "start_interval": "09:45:00",
        "end_interval": "10:00:00",
        "chart_id": 1,
        "client_id": 1,
        "activity": "Lunch",
        "interval_tags": {"Non-Compliance": 5, "Throwing": 2},
        "interval_rating": 1,
        "interval_notes": "Refused to eat lunch, seeking attention from classmates",
    },
    {
        "id": 9,
        "start_interval": "10:00:00",
        "end_interval": "10:15:00",
        "chart_id": 1,
        "client_id": 1,
        "activity": "Snack",
        "interval_tags": {"Task Refusal": 3},
        "interval_rating": 3,
        "interval_notes": "Refused snack, seeking escape from activity",
    },
    {
        "id": 10,
        "start_interval": "10:15:00",
        "end_interval": "10:30:00",
        "chart_id": 1,
        "client_id": 1,
        "activity": "Music",
        "interval_tags": {"Inattention": 4, "Outbursts": 3},
        "interval_rating": 2,
        "interval_notes": "Distracted during music lesson, seeking attention",
    },
    #
    {
        "id": 11,
        "start_interval": "08:00:00",
        "end_interval": "08:15:00",
        "chart_id": 2,
        "client_id": 2,
        "activity": "Circle Time",
        "interval_tags": {"Tantrums": 5, "Hitting": 1},
        "interval_rating": 1,
        "interval_notes": "Tantrum when asked to participate in circle time",
    },
    {
        "id": 12,
        "start_interval": "08:15:00",
        "end_interval": "08:30:00",
        "chart_id": 2,
        "client_id": 2,
        "activity": "Snack",
        "interval_tags": {"Self-Injurious Behavior": 3},
        "interval_rating": 1,
        "interval_notes": "Engaged in self-hitting behavior during snack time",
    },
    {
        "id": 13,
        "start_interval": "08:30:00",
        "end_interval": "08:45:00",
        "chart_id": 2,
        "client_id": 2,
        "activity": "P.E.",
        "interval_tags": {"Elopement": 1},
        "interval_rating": 1,
        "interval_notes": "Attempted to leave gymnasium during physical education",
    },
    {
        "id": 14,
        "start_interval": "08:45:00",
        "end_interval": "09:00:00",
        "chart_id": 2,
        "client_id": 2,
        "activity": "Recess",
        "interval_tags": {"Vocal Stereotypy": 4},
        "interval_rating": 1,
        "interval_notes": "Vocal stimming behavior during outdoor play",
    },
    {
        "id": 15,
        "start_interval": "09:00:00",
        "end_interval": "09:15:00",
        "chart_id": 2,
        "client_id": 2,
        "activity": "Writing",
        "interval_tags": {"Task Refusal": 5},
        "interval_rating": 1,
        "interval_notes": "Refused to complete writing assignment, seeking escape",
    },
    {
        "id": 16,
        "start_interval": "09:15:00",
        "end_interval": "09:30:00",
        "chart_id": 2,
        "client_id": 2,
        "activity": "Science",
        "interval_tags": {"Non-Compliance": 4},
        "interval_rating": 1,
        "interval_notes": "Ignored teacher's instructions during science experiment",
    },
    {
        "id": 17,
        "start_interval": "09:30:00",
        "end_interval": "09:45:00",
        "chart_id": 2,
        "client_id": 2,
        "activity": "Reading",
        "interval_tags": {"Task Refusal": 4, "Elopement": 1},
        "interval_rating": 2,
        "interval_notes": "Refused to participate in reading activity, seeking escape",
    },
    {
        "id": 18,
        "start_interval": "09:45:00",
        "end_interval": "10:00:00",
        "chart_id": 2,
        "client_id": 2,
        "activity": "Music",
        "interval_tags": {"Inattention": 3},
        "interval_rating": 4,
        "interval_notes": "Distracted during music lesson",
    },
    {
        "id": 19,
        "start_interval": "10:00:00",
        "end_interval": "10:15:00",
        "chart_id": 2,
        "client_id": 2,
        "activity": "Lunch",
        "interval_tags": {},
        "interval_rating": 5,
        "interval_notes": "Ate lunch without any problem behavior, well done!",
    },
    {
        "id": 20,
        "start_interval": "10:15:00",
        "end_interval": "10:30:00",
        "chart_id": 2,
        "client_id": 2,
        "activity": "Art",
        "interval_tags": {},
        "interval_rating": 5,
        "interval_notes": "Engaged well in art activity, no problem behaviors observed",
    },
    {
        "id": 21,
        "start_interval": "10:30:00",
        "end_interval": "10:45:00",
        "chart_id": 2,
        "client_id": 2,
        "activity": "Snack",
        "interval_tags": {},
        "interval_rating": 5,
        "interval_notes": "Ate snack without any problem behavior, great job!",
    },
    {
        "id": 22,
        "start_interval": "10:45:00",
        "end_interval": "11:00:00",
        "chart_id": 2,
        "client_id": 2,
        "activity": "Circle Time",
        "interval_tags": {},
        "interval_rating": 4,
        "interval_notes": "Participated well in circle time, minimal redirection needed",
    },
    {
        "id": 31,
        "start_interval": "08:00:00",
        "end_interval": "08:15:00",
        "chart_id": 3,
        "client_id": 3,
        "activity": "Math",
        "interval_tags": {"Non-Compliance": 5},
        "interval_rating": 2,
        "interval_notes": "Refused to engage in math activity",
    },
    {
        "id": 32,
        "start_interval": "08:15:00",
        "end_interval": "08:30:00",
        "chart_id": 3,
        "client_id": 3,
        "activity": "Recess",
        "interval_tags": {"Aggression": 3},
        "interval_rating": 3,
        "interval_notes": "Engaged in aggressive behavior towards peers",
    },
    {
        "id": 33,
        "start_interval": "08:30:00",
        "end_interval": "08:45:00",
        "chart_id": 3,
        "client_id": 3,
        "activity": "Art",
        "interval_tags": {"Property Destruction": 4},
        "interval_rating": 1,
        "interval_notes": "Destroyed art supplies during activity",
    },
    {
        "id": 34,
        "start_interval": "08:45:00",
        "end_interval": "09:00:00",
        "chart_id": 3,
        "client_id": 3,
        "activity": "Circle Time",
        "interval_tags": {"Non-Compliance": 3},
        "interval_rating": 1,
        "interval_notes": "Refused to participate in circle time",
    },
    {
        "id": 35,
        "start_interval": "09:00:00",
        "end_interval": "09:15:00",
        "chart_id": 3,
        "client_id": 3,
        "activity": "Lunch",
        "interval_tags": {"Food Refusal": 5},
        "interval_rating": 1,
        "interval_notes": "Refused to eat lunch, seeking attention",
    },
    {
        "id": 36,
        "start_interval": "09:15:00",
        "end_interval": "09:30:00",
        "chart_id": 3,
        "client_id": 3,
        "activity": "P.E.",
        "interval_tags": {"Elopement": 4},
        "interval_rating": 1,
        "interval_notes": "Attempted to leave gymnasium during physical education",
    },
    {
        "id": 37,
        "start_interval": "09:30:00",
        "end_interval": "09:45:00",
        "chart_id": 3,
        "client_id": 3,
        "activity": "Science",
        "interval_tags": {"Task Refusal": 4},
        "interval_rating": 3,
        "interval_notes": "Refused to participate in science experiment, seeking escape",
    },
    {
        "id": 38,
        "start_interval": "09:45:00",
        "end_interval": "10:00:00",
        "chart_id": 3,
        "client_id": 3,
        "activity": "Art",
        "interval_tags": {"Non-Compliance": 5},
        "interval_rating": 1,
        "interval_notes": "Ignored teacher's instructions during art activity",
    },
    {
        "id": 39,
        "start_interval": "10:00:00",
        "end_interval": "10:15:00",
        "chart_id": 3,
        "client_id": 3,
        "activity": "Snack",
        "interval_tags": {"Task Refusal": 3},
        "interval_rating": 3,
        "interval_notes": "Refused snack, seeking escape from activity",
    },
    {
        "id": 40,
        "start_interval": "10:15:00",
        "end_interval": "10:30:00",
        "chart_id": 3,
        "client_id": 3,
        "activity": "Reading",
        "interval_tags": {"Inattention": 4},
        "interval_rating": 2,
        "interval_notes": "Distracted during reading, seeking attention",
    },
    {
        "id": 41,
        "start_interval": "10:30:00",
        "end_interval": "10:45:00",
        "chart_id": 3,
        "client_id": 3,
        "activity": "Math",
        "interval_tags": {"Non-Compliance": 3},
        "interval_rating": 3,
        "interval_notes": "Refused to engage in math activity, seeking escape",
    },
    {
        "id": 42,
        "start_interval": "10:45:00",
        "end_interval": "11:00:00",
        "chart_id": 3,
        "client_id": 3,
        "activity": "Circle Time",
        "interval_tags": {"Aggression": 4},
        "interval_rating": 1,
        "interval_notes": "Engaged in aggressive behavior towards classmates",
    },
    {
        "id": 11,
        "start_interval": "08:00:00",
        "end_interval": "08:15:00",
        "chart_id": 4,
        "client_id": 1,
        "activity": "Circle Time",
        "interval_tags": {"Inattention": 3},
        "interval_rating": 3,
        "therapist_id": 1,
        "interval_notes": "Distracted during circle time, seeking attention",
    },
    {
        "id": 12,
        "start_interval": "08:15:00",
        "end_interval": "08:30:00",
        "chart_id": 4,
        "client_id": 1,
        "activity": "Recess",
        "interval_tags": {},
        "interval_rating": 5,
        "therapist_id": 1,
        "interval_notes": "Engaged positively in outdoor play, no problem behaviors observed",
    },
    {
        "id": 13,
        "start_interval": "08:30:00",
        "end_interval": "08:45:00",
        "chart_id": 4,
        "client_id": 1,
        "activity": "Art",
        "interval_tags": {"Inattention": 2},
        "interval_rating": 4,
        "therapist_id": 1,
        "interval_notes": "Minor distraction during art activity, quickly redirected",
    },
    {
        "id": 14,
        "start_interval": "08:45:00",
        "end_interval": "09:00:00",
        "chart_id": 4,
        "client_id": 1,
        "activity": "Math",
        "interval_tags": {"Non-Compliance": 2},
        "interval_rating": 4,
        "therapist_id": 1,
        "interval_notes": "Initially resisted math activity but complied after redirection",
    },
    {
        "id": 15,
        "start_interval": "09:00:00",
        "end_interval": "09:15:00",
        "chart_id": 4,
        "client_id": 1,
        "activity": "Science",
        "interval_tags": {},
        "interval_rating": 5,
        "therapist_id": 1,
        "interval_notes": "Engaged actively in science experiment, no problem behaviors observed",
    },
    {
        "id": 16,
        "start_interval": "09:15:00",
        "end_interval": "09:30:00",
        "chart_id": 4,
        "client_id": 1,
        "activity": "P.E.",
        "interval_tags": {},
        "interval_rating": 5,
        "therapist_id": 1,
        "interval_notes": "Participated enthusiastically in physical education, no problem behaviors observed",
    },
    {
        "id": 17,
        "start_interval": "09:30:00",
        "end_interval": "09:45:00",
        "chart_id": 4,
        "client_id": 1,
        "activity": "Reading",
        "interval_tags": {"Inattention": 1},
        "interval_rating": 4,
        "therapist_id": 1,
        "interval_notes": "Slightly distracted during reading, quickly refocused",
    },
    {
        "id": 18,
        "start_interval": "09:45:00",
        "end_interval": "10:00:00",
        "chart_id": 4,
        "client_id": 1,
        "activity": "Lunch",
        "interval_tags": {},
        "interval_rating": 5,
        "therapist_id": 1,
        "interval_notes": "Ate lunch without any problem behavior, well done!",
    },
    {
        "id": 19,
        "start_interval": "10:00:00",
        "end_interval": "10:15:00",
        "chart_id": 4,
        "client_id": 1,
        "activity": "Snack",
        "interval_tags": {"Task Refusal": 1},
        "interval_rating": 4,
        "therapist_id": 1,
        "interval_notes": "Briefly refused snack, complied after gentle encouragement",
    },
    {
        "id": 20,
        "start_interval": "10:15:00",
        "end_interval": "10:30:00",
        "chart_id": 4,
        "client_id": 1,
        "activity": "Music",
        "interval_tags": {"Inattention": 2},
        "interval_rating": 4,
        "therapist_id": 1,
        "interval_notes": "Minor distraction during music lesson, redirected quickly",
    },
    {
        "id": 21,
        "start_interval": "10:30:00",
        "end_interval": "10:45:00",
        "chart_id": 4,
        "client_id": 1,
        "activity": "Social Studies",
        "interval_tags": {},
        "interval_rating": 5,
        "therapist_id": 1,
        "interval_notes": "Engaged well in social studies discussion, no problem behaviors observed",
    },
    {
        "id": 22,
        "start_interval": "10:45:00",
        "end_interval": "11:00:00",
        "chart_id": 4,
        "client_id": 1,
        "activity": "Free Time",
        "interval_tags": {},
        "interval_rating": 5,
        "therapist_id": 1,
        "interval_notes": "Enjoyed free time activities without any problem behaviors",
    },
    {
        "id": 13,
        "start_interval": "08:00:00",
        "end_interval": "08:15:00",
        "chart_id": 5,
        "client_id": 2,
        "activity": "Circle Time",
        "interval_tags": {"Inattention": 4},
        "interval_rating": 3,
        "therapist_id": 1,
        "interval_notes": "Distracted during circle time, required redirection",
    },
    {
        "id": 14,
        "start_interval": "08:15:00",
        "end_interval": "08:30:00",
        "chart_id": 5,
        "client_id": 2,
        "activity": "Recess",
        "interval_tags": {"Non-Compliance": 2},
        "interval_rating": 4,
        "therapist_id": 1,
        "interval_notes": "Resisted joining group game during recess, complied after prompting",
    },
    {
        "id": 15,
        "start_interval": "08:30:00",
        "end_interval": "08:45:00",
        "chart_id": 5,
        "client_id": 2,
        "activity": "Art",
        "interval_tags": {"Task Refusal": 3},
        "interval_rating": 2,
        "therapist_id": 1,
        "interval_notes": "Initially refused to start art project, required encouragement to begin",
    },
    {
        "id": 16,
        "start_interval": "08:45:00",
        "end_interval": "09:00:00",
        "chart_id": 5,
        "client_id": 2,
        "activity": "Math",
        "interval_tags": {"Inattention": 5},
        "interval_rating": 1,
        "therapist_id": 1,
        "interval_notes": "Severely distracted during math activity, struggled to focus",
    },
    {
        "id": 17,
        "start_interval": "09:00:00",
        "end_interval": "09:15:00",
        "chart_id": 5,
        "client_id": 2,
        "activity": "Science",
        "interval_tags": {"Task Refusal": 2},
        "interval_rating": 3,
        "therapist_id": 1,
        "interval_notes": "Initially refused to participate in science experiment, complied after explanation",
    },
    {
        "id": 18,
        "start_interval": "09:15:00",
        "end_interval": "09:30:00",
        "client_id": 2,
        "chart_id": 5,
        "activity": "P.E.",
        "interval_tags": {},
        "interval_rating": 5,
        "therapist_id": 1,
        "interval_notes": "Active participation in physical education, no problem behaviors observed",
    },
    {
        "id": 19,
        "start_interval": "09:30:00",
        "end_interval": "09:45:00",
        "client_id": 2,
        "chart_id": 5,
        "activity": "Reading",
        "interval_tags": {"Inattention": 3},
        "interval_rating": 4,
        "therapist_id": 1,
        "interval_notes": "Slightly distracted during reading, redirected quickly",
    },
    {
        "id": 20,
        "start_interval": "09:45:00",
        "end_interval": "10:00:00",
        "client_id": 2,
        "chart_id": 5,
        "activity": "Lunch",
        "interval_tags": {},
        "interval_rating": 5,
        "therapist_id": 1,
        "interval_notes": "Ate lunch without any problem behavior, well done!",
    },
    {
        "id": 21,
        "start_interval": "10:00:00",
        "end_interval": "10:15:00",
        "client_id": 2,
        "chart_id": 5,
        "activity": "Snack",
        "interval_tags": {"Inattention": 1},
        "interval_rating": 4,
        "therapist_id": 1,
        "interval_notes": "Minor distraction during snack time, quickly refocused",
    },
    {
        "id": 22,
        "start_interval": "10:15:00",
        "end_interval": "10:30:00",
        "client_id": 2,
        "chart_id": 5,
        "activity": "Music",
        "interval_tags": {"Inattention": 4},
        "interval_rating": 3,
        "therapist_id": 1,
        "interval_notes": "Distracted during music lesson, required redirection",
    },
    {
        "id": 23,
        "start_interval": "10:30:00",
        "end_interval": "10:45:00",
        "client_id": 2,
        "chart_id": 5,
        "activity": "Social Studies",
        "interval_tags": {"Non-Compliance": 1},
        "interval_rating": 4,
        "therapist_id": 1,
        "interval_notes": "Momentarily resisted participating in social studies activity, complied after prompt",
    },
    {
        "id": 24,
        "start_interval": "10:45:00",
        "end_interval": "11:00:00",
        "client_id": 2,
        "chart_id": 5,
        "activity": "Free Time",
        "interval_tags": {},
        "interval_rating": 5,
        "therapist_id": 1,
        "interval_notes": "Enjoyed free time activities without any problem behaviors",
    },
    {
        "id": 13,
        "start_interval": "08:00:00",
        "end_interval": "08:15:00",
        "client_id": 3,
        "chart_id": 6,
        "activity": "Circle Time",
        "interval_tags": {"Non-Compliance": 4},
        "interval_rating": 2,
        "therapist_id": 1,
        "interval_notes": "Refused to sit during circle time, disruptive behavior observed",
    },
    {
        "id": 14,
        "start_interval": "08:15:00",
        "end_interval": "08:30:00",
        "client_id": 3,
        "chart_id": 6,
        "activity": "Recess",
        "interval_tags": {"Aggression": 1},
        "interval_rating": 1,
        "therapist_id": 1,
        "interval_notes": "Engaged in aggressive behavior towards peer during recess",
    },
    {
        "id": 15,
        "start_interval": "08:30:00",
        "end_interval": "08:45:00",
        "client_id": 3,
        "chart_id": 6,
        "activity": "Art",
        "interval_tags": {"Task Refusal": 3},
        "interval_rating": 2,
        "therapist_id": 1,
        "interval_notes": "Refused to participate in art activity, seeking escape",
    },
    {
        "id": 16,
        "start_interval": "08:45:00",
        "end_interval": "09:00:00",
        "client_id": 3,
        "chart_id": 6,
        "activity": "Math",
        "interval_tags": {"Non-Compliance": 5},
        "interval_rating": 1,
        "therapist_id": 1,
        "interval_notes": "Continuously refused to engage in math activity, defiance observed",
    },
    {
        "id": 17,
        "start_interval": "09:00:00",
        "end_interval": "09:15:00",
        "client_id": 3,
        "chart_id": 6,
        "activity": "Science",
        "interval_tags": {"Task Refusal": 2},
        "interval_rating": 2,
        "therapist_id": 1,
        "interval_notes": "Initially refused to participate in science experiment, complied reluctantly",
    },
    {
        "id": 18,
        "start_interval": "09:15:00",
        "end_interval": "09:30:00",
        "client_id": 3,
        "chart_id": 6,
        "activity": "P.E.",
        "interval_tags": {"Non-Compliance": 3},
        "interval_rating": 2,
        "therapist_id": 1,
        "interval_notes": "Ignored instructions during physical education class, defiance observed",
    },
    {
        "id": 19,
        "start_interval": "09:30:00",
        "end_interval": "09:45:00",
        "client_id": 3,
        "chart_id": 6,
        "activity": "Reading",
        "interval_tags": {"Inattention": 3},
        "interval_rating": 3,
        "therapist_id": 1,
        "interval_notes": "Distracted during reading, required redirection",
    },
    {
        "id": 20,
        "start_interval": "09:45:00",
        "end_interval": "10:00:00",
        "client_id": 3,
        "chart_id": 6,
        "activity": "Lunch",
        "interval_tags": {},
        "interval_rating": 5,
        "therapist_id": 1,
        "interval_notes": "Ate lunch without any problem behavior, well done!",
    },
    {
        "id": 21,
        "start_interval": "10:00:00",
        "end_interval": "10:15:00",
        "client_id": 3,
        "chart_id": 6,
        "activity": "Snack",
        "interval_tags": {"Task Refusal": 2},
        "interval_rating": 3,
        "therapist_id": 1,
        "interval_notes": "Initially refused snack, complied after encouragement",
    },
    {
        "id": 22,
        "start_interval": "10:15:00",
        "end_interval": "10:30:00",
        "client_id": 3,
        "chart_id": 6,
        "activity": "Music",
        "interval_tags": {"Inattention": 4},
        "interval_rating": 2,
        "therapist_id": 1,
        "interval_notes": "Distracted during music lesson, required redirection",
    },
    {
        "id": 16,
        "start_interval": "08:00:00",
        "end_interval": "08:15:00",
        "client_id": 1,
        "chart_id": 7,
        "activity": "Circle Time",
        "interval_tags": {"Inattention": 4},
        "interval_rating": 3,
        "therapist_id": 1,
        "interval_notes": "Slightly distracted during circle time, required redirection",
    },
    {
        "id": 17,
        "start_interval": "08:15:00",
        "end_interval": "08:30:00",
        "client_id": 1,
        "chart_id": 7,
        "activity": "Recess",
        "interval_tags": {"Non-Compliance": 2},
        "interval_rating": 4,
        "therapist_id": 1,
        "interval_notes": "Resisted joining group game during recess, complied after prompting",
    },
    {
        "id": 18,
        "start_interval": "08:30:00",
        "end_interval": "08:45:00",
        "client_id": 1,
        "chart_id": 7,
        "activity": "Art",
        "interval_tags": {"Task Refusal": 3},
        "interval_rating": 2,
        "therapist_id": 1,
        "interval_notes": "Refused to participate in art activity, required encouragement",
    },
    {
        "id": 19,
        "start_interval": "08:45:00",
        "end_interval": "09:00:00",
        "client_id": 1,
        "chart_id": 7,
        "activity": "Math",
        "interval_tags": {"Inattention": 5},
        "interval_rating": 1,
        "therapist_id": 1,
        "interval_notes": "Distracted during math activity, struggled to focus",
    },
    {
        "id": 20,
        "start_interval": "09:00:00",
        "end_interval": "09:15:00",
        "client_id": 1,
        "chart_id": 7,
        "activity": "Science",
        "interval_tags": {"Task Refusal": 2},
        "interval_rating": 3,
        "therapist_id": 1,
        "interval_notes": "Initially refused to participate in science experiment, complied after explanation",
    },
    {
        "id": 21,
        "start_interval": "09:15:00",
        "end_interval": "09:30:00",
        "client_id": 1,
        "chart_id": 7,
        "activity": "P.E.",
        "interval_tags": {},
        "interval_rating": 5,
        "therapist_id": 1,
        "interval_notes": "Active participation in physical education, no problem behaviors observed",
    },
    {
        "id": 22,
        "start_interval": "09:30:00",
        "end_interval": "09:45:00",
        "client_id": 1,
        "chart_id": 7,
        "activity": "Reading",
        "interval_tags": {"Inattention": 3},
        "interval_rating": 4,
        "therapist_id": 1,
        "interval_notes": "Slightly distracted during reading, required redirection",
    },
    {
        "id": 23,
        "start_interval": "09:45:00",
        "end_interval": "10:00:00",
        "client_id": 1,
        "chart_id": 7,
        "activity": "Lunch",
        "interval_tags": {},
        "interval_rating": 5,
        "therapist_id": 1,
        "interval_notes": "Ate lunch without any problem behavior, well done!",
    },
    {
        "id": 24,
        "start_interval": "10:00:00",
        "end_interval": "10:15:00",
        "client_id": 1,
        "chart_id": 7,
        "activity": "Snack",
        "interval_tags": {"Inattention": 1},
        "interval_rating": 4,
        "therapist_id": 1,
        "interval_notes": "Minor distraction during snack time, quickly refocused",
    },
    {
        "id": 25,
        "start_interval": "10:15:00",
        "end_interval": "10:30:00",
        "client_id": 1,
        "chart_id": 7,
        "activity": "Music",
        "interval_tags": {"Inattention": 4},
        "interval_rating": 3,
        "therapist_id": 1,
        "interval_notes": "Distracted during music lesson, required redirection",
    },
    {
        "id": 26,
        "start_interval": "08:00:00",
        "end_interval": "08:15:00",
        "client_id": 2,
        "chart_id": 8,
        "activity": "Circle Time",
        "interval_tags": {"Inattention": 3},
        "interval_rating": 4,
        "therapist_id": 2,
        "interval_notes": "Minor distraction during circle time, quickly refocused",
    },
    {
        "id": 27,
        "start_interval": "08:15:00",
        "end_interval": "08:30:00",
        "client_id": 2,
        "chart_id": 8,
        "activity": "Recess",
        "interval_tags": {},
        "interval_rating": 5,
        "therapist_id": 2,
        "interval_notes": "Participated actively during recess, no problem behaviors observed",
    },
    {
        "id": 28,
        "start_interval": "08:30:00",
        "end_interval": "08:45:00",
        "client_id": 2,
        "chart_id": 8,
        "activity": "Art",
        "interval_tags": {"Task Refusal": 2},
        "interval_rating": 3,
        "therapist_id": 2,
        "interval_notes": "Initially reluctant to start art project, complied after encouragement",
    },
    {
        "id": 29,
        "start_interval": "08:45:00",
        "end_interval": "09:00:00",
        "client_id": 2,
        "chart_id": 8,
        "activity": "Math",
        "interval_tags": {"Inattention": 4},
        "interval_rating": 3,
        "therapist_id": 2,
        "interval_notes": "Slightly distracted during math activity, required redirection",
    },
    {
        "id": 30,
        "start_interval": "09:00:00",
        "end_interval": "09:15:00",
        "client_id": 2,
        "chart_id": 8,
        "activity": "Science",
        "interval_tags": {"Task Refusal": 3},
        "interval_rating": 2,
        "therapist_id": 2,
        "interval_notes": "Resisted participating in science experiment, required persuasion",
    },
    {
        "id": 31,
        "start_interval": "09:15:00",
        "end_interval": "09:30:00",
        "client_id": 2,
        "chart_id": 8,
        "activity": "P.E.",
        "interval_tags": {"Non-Compliance": 2},
        "interval_rating": 3,
        "therapist_id": 2,
        "interval_notes": "Partially ignored instructions during physical education class, corrected behavior",
    },
    {
        "id": 32,
        "start_interval": "09:30:00",
        "end_interval": "09:45:00",
        "client_id": 2,
        "chart_id": 8,
        "activity": "Reading",
        "interval_tags": {"Inattention": 4},
        "interval_rating": 2,
        "therapist_id": 2,
        "interval_notes": "Distracted during reading, required redirection",
    },
    {
        "id": 33,
        "start_interval": "09:45:00",
        "end_interval": "10:00:00",
        "client_id": 2,
        "chart_id": 8,
        "activity": "Lunch",
        "interval_tags": {},
        "interval_rating": 5,
        "therapist_id": 2,
        "interval_notes": "Ate lunch without any problem behavior, well done!",
    },
    {
        "id": 34,
        "start_interval": "10:00:00",
        "end_interval": "10:15:00",
        "client_id": 2,
        "chart_id": 8,
        "activity": "Snack",
        "interval_tags": {"Inattention": 3},
        "interval_rating": 4,
        "therapist_id": 2,
        "interval_notes": "Slightly distracted during snack time, quickly refocused",
    },
    {
        "id": 35,
        "start_interval": "10:15:00",
        "end_interval": "10:30:00",
        "client_id": 2,
        "chart_id": 8,
        "activity": "Music",
        "interval_tags": {"Inattention": 2},
        "interval_rating": 4,
        "therapist_id": 2,
        "interval_notes": "Minor distraction during music lesson, quickly refocused",
    },
    {
        "id": 36,
        "start_interval": "08:00:00",
        "end_interval": "08:15:00",
        "client_id": 3,
        "chart_id": 9,
        "activity": "Circle Time",
        "interval_tags": {"Vocal Stereotypy": 2},
        "interval_rating": 3,
        "therapist_id": 3,
        "interval_notes": "Engaged in vocal stereotypy behavior during circle time, redirected successfully",
    },
    {
        "id": 37,
        "start_interval": "08:15:00",
        "end_interval": "08:30:00",
        "client_id": 3,
        "chart_id": 9,
        "activity": "Recess",
        "interval_tags": {"Elopement": 1},
        "interval_rating": 2,
        "therapist_id": 3,
        "interval_notes": "Attempted to leave the playground area during recess, quickly redirected back",
    },
    {
        "id": 38,
        "start_interval": "08:30:00",
        "end_interval": "08:45:00",
        "client_id": 3,
        "chart_id": 9,
        "activity": "Art",
        "interval_tags": {"Task Refusal": 3},
        "interval_rating": 2,
        "therapist_id": 3,
        "interval_notes": "Reluctant to participate in art activity, required encouragement",
    },
    {
        "id": 39,
        "start_interval": "08:45:00",
        "end_interval": "09:00:00",
        "client_id": 3,
        "chart_id": 9,
        "activity": "Math",
        "interval_tags": {"Non-Compliance": 2},
        "interval_rating": 3,
        "therapist_id": 3,
        "interval_notes": "Partial compliance during math activity, required additional prompting",
    },
    {
        "id": 40,
        "start_interval": "09:00:00",
        "end_interval": "09:15:00",
        "client_id": 3,
        "chart_id": 9,
        "activity": "Science",
        "interval_tags": {},
        "interval_rating": 5,
        "therapist_id": 3,
        "interval_notes": "Active participation in science experiment, no problem behaviors observed",
    },
    {
        "id": 41,
        "start_interval": "09:15:00",
        "end_interval": "09:30:00",
        "client_id": 3,
        "chart_id": 9,
        "activity": "P.E.",
        "interval_tags": {"Non-Compliance": 2},
        "interval_rating": 3,
        "therapist_id": 3,
        "interval_notes": "Partially ignored instructions during physical education class, corrected behavior",
    },
    {
        "id": 42,
        "start_interval": "09:30:00",
        "end_interval": "09:45:00",
        "client_id": 3,
        "chart_id": 9,
        "activity": "Reading",
        "interval_tags": {"Inattention": 3},
        "interval_rating": 4,
        "therapist_id": 3,
        "interval_notes": "Minor distraction during reading, quickly refocused",
    },
    {
        "id": 43,
        "start_interval": "09:45:00",
        "end_interval": "10:00:00",
        "client_id": 3,
        "chart_id": 9,
        "activity": "Lunch",
        "interval_tags": {},
        "interval_rating": 5,
        "therapist_id": 3,
        "interval_notes": "Ate lunch without any problem behavior, well done!",
    },
    {
        "id": 44,
        "start_interval": "10:00:00",
        "end_interval": "10:15:00",
        "client_id": 3,
        "chart_id": 9,
        "activity": "Snack",
        "interval_tags": {},
        "interval_rating": 5,
        "therapist_id": 3,
        "interval_notes": "Enjoyed snack without any problem behavior, great job!",
    },
    {
        "id": 45,
        "start_interval": "10:15:00",
        "end_interval": "10:30:00",
        "client_id": 3,
        "chart_id": 9,
        "activity": "Music",
        "interval_tags": {"Task Refusal": 2},
        "interval_rating": 3,
        "therapist_id": 3,
        "interval_notes": "Initially reluctant to participate in music activity, complied after encouragement",
    },
]
