Interval = [{
      "id": 1,
      "start_interval": "2024-04-28T08:00:00",
      "end_interval": "2024-04-28T08:15:00",
      "client_id":1,
      "client_id": 1,
      "activity": "Math",
      "interval_tags": {"Inattention": 5},
      "interval_rating": 2,
      "therapist_id":1,
      "interval_notes": "Difficulty focusing, seeking attention from peers"
    },
    {
      "id": 2,
      "start_interval": "2024-04-28T08:15:00",
      "end_interval": "2024-04-28T08:30:00",
      "client_id":1,
      "client_id": 1,
      "activity": "Recess",
      "interval_tags": {"Non-Compliance": 3},
      "interval_rating": 3,
      "therapist_id":1,
      "interval_notes": "Refused to participate in organized game"
    },
    {
      "id": 3,
      "start_interval": "2024-04-28T08:30:00",
      "end_interval": "2024-04-28T08:45:00",
      "client_id":1,
      "client_id": 1,
      "activity": "Art",
      "interval_tags": {"Task Refusal": 4,"Elopement":1},
      "interval_rating": 1,
      "therapist_id":1,
      "interval_notes": "Refused to start art project, seeking escape from activity"
    },
    {
      "id": 4,
      "start_interval": "2024-04-28T08:45:00",
      "end_interval": "2024-04-28T09:00:00",
      "client_id":1,
      "client_id": 1,
      "activity": "Circle Time",
      "interval_tags": {"Outbursts": 3},
      "interval_rating": 1,
      "therapist_id":1,
      "interval_notes": "Disrupted circle time with loud outburst"
    },
    {
      "id": 5,
      "start_interval": "2024-04-28T09:00:00",
      "end_interval": "2024-04-28T09:15:00",
      "client_id":1,
      "client_id": 1,
      "activity": "Science",
      "interval_tags": {"Task Refusal": 5},
      "interval_rating": 1,
      "therapist_id":1,
      "interval_notes": "Refused to participate in science experiment"
    },
    {
      "id": 6,
      "start_interval": "2024-04-28T09:15:00",
      "end_interval": "2024-04-28T09:30:00",
      "client_id":1,
      "client_id": 1,
      "activity": "P.E.",
      "interval_tags": {"Non-Compliance": 4},
      "interval_rating": 1,
      "therapist_id":1,
      "interval_notes": "Ignored teacher's instructions during physical activity"
    },
    {
      "id": 7,
      "start_interval": "2024-04-28T09:30:00",
      "end_interval": "2024-04-28T09:45:00",
      "client_id":1,
      "client_id": 1,
      "activity": "Reading",
      "interval_tags": {"Inattention": 4},
      "interval_rating": 3,
      "therapist_id":1,
      "interval_notes": "Distracted during reading, seeking attention from teacher"
    },
    {
      "id": 8,
      "start_interval": "2024-04-28T09:45:00",
      "end_interval": "2024-04-28T10:00:00",
      "client_id":1,
      "client_id": 1,
      "activity": "Lunch",
      "interval_tags": {"Non-Compliance": 5,"Throwing": 2},
      "interval_rating": 1,
      "therapist_id":1,
      "interval_notes": "Refused to eat lunch, seeking attention from classmates"
    },
    {
      "id": 9,
      "start_interval": "2024-04-28T10:00:00",
      "end_interval": "2024-04-28T10:15:00",
      "client_id":1,
      "client_id": 1,
      "activity": "Snack",
      "interval_tags": {"Task Refusal": 3},
      "interval_rating": 3,
      "therapist_id":1,
      "interval_notes": "Refused snack, seeking escape from activity"
    },
    {
      "id": 10,
      "start_interval": "2024-04-28T10:15:00",
      "end_interval": "2024-04-28T10:30:00",
      "client_id":1,
      "client_id": 1,
      "activity": "Music",
      "interval_tags": {"Inattention": 4,"Outbursts": 3},
      "interval_rating": 2,
      "therapist_id":1,
      "interval_notes": "Distracted during music lesson, seeking attention"
    },




    {
      "id": 11,
      "start_interval": "2024-04-28T08:00:00",
      "end_interval": "2024-04-28T08:15:00",
      "client_id":2,
      "client_id": 2,
      "activity": "Circle Time",
      "interval_tags": {"Tantrums": 5,"Hitting": 1},
      "interval_rating": 1,
      "client_id": 1,
      "interval_notes": "Tantrum when asked to participate in circle time"
    },
    {
      "id": 12,
      "start_interval": "2024-04-28T08:15:00",
      "end_interval": "2024-04-28T08:30:00",
      "client_id":2,
      "client_id": 2,
      "activity": "Snack",
      "interval_tags": {"Self-Injurious Behavior": 3},
      "interval_rating": 1,
      "client_id": 1,
      "interval_notes": "Engaged in self-hitting behavior during snack time"
    },
    {
      "id": 13,
      "start_interval": "2024-04-28T08:30:00",
      "end_interval": "2024-04-28T08:45:00",
      "client_id":2,
      "client_id": 2,
      "activity": "P.E.",
      "interval_tags": {"Elopement": 1},
      "interval_rating": 1,
      "client_id": 1,
      "interval_notes": "Attempted to leave gymnasium during physical education"
    },
    {
      "id": 14,
      "start_interval": "2024-04-28T08:45:00",
      "end_interval": "2024-04-28T09:00:00",
      "client_id":2,
      "client_id": 2,
      "activity": "Recess",
      "interval_tags": {"Vocal Stereotypy": 4},
      "interval_rating": 1,
      "client_id": 1,
      "interval_notes": "Vocal stimming behavior during outdoor play"
    },
    {
      "id": 15,
      "start_interval": "2024-04-28T09:00:00",
      "end_interval": "2024-04-28T09:15:00",
      "client_id":2,
      "client_id": 2,
      "activity": "Writing",
      "interval_tags": {"Task Refusal": 5},
      "interval_rating": 1,
      "client_id": 1,
      "interval_notes": "Refused to complete writing assignment, seeking escape"
    },
    {
      "id": 16,
      "start_interval": "2024-04-28T09:15:00",
      "end_interval": "2024-04-28T09:30:00",
      "client_id":2,
      "client_id": 2,
      "activity": "Science",
      "interval_tags": {"Non-Compliance": 4},
      "interval_rating": 1,
      "client_id": 1,
      "interval_notes": "Ignored teacher's instructions during science experiment"
    },
    {
      "id": 17,
      "start_interval": "2024-04-28T09:30:00",
      "end_interval": "2024-04-28T09:45:00",
      "client_id":2,
      "client_id": 2,
      "activity": "Reading",
      "interval_tags": {"Task Refusal": 4,"Elopement":1},
      "interval_rating": 2,
      "client_id": 1,
      "interval_notes": "Refused to participate in reading activity, seeking escape"
    },
    {
      "id": 18,
      "start_interval": "2024-04-28T09:45:00",
      "end_interval": "2024-04-28T10:00:00",
      "client_id":2,
      "client_id": 2,
      "activity": "Music",
      "interval_tags": {"Inattention": 3},
      "interval_rating": 4,
      "client_id": 1,
      "interval_notes": "Distracted during music lesson"
    },
    {
      "id": 19,
      "start_interval": "2024-04-28T10:00:00",
      "end_interval": "2024-04-28T10:15:00",
      "client_id":2,
      "client_id": 2,
      "activity": "Lunch",
      "interval_rating": 5,
      "client_id": 1,
      "interval_notes": "Ate lunch without any problem behavior, well done!"
    },
    {
      "id": 20,
      "start_interval": "2024-04-28T10:15:00",
      "end_interval": "2024-04-28T10:30:00",
      "client_id":2,
      "client_id": 2,
      "activity": "Art",
      "interval_rating": 5,
      "client_id": 1,
      "interval_notes": "Engaged well in art activity, no problem behaviors observed"
    },
    {
      "id": 21,
      "start_interval": "2024-04-28T10:30:00",
      "end_interval": "2024-04-28T10:45:00",
      "client_id":2,
      "client_id": 2,
      "activity": "Snack",
      "interval_rating": 5,
      "client_id": 1,
      "interval_notes": "Ate snack without any problem behavior, great job!"
    },
    {
      "id": 22,
      "start_interval": "2024-04-28T10:45:00",
      "end_interval": "2024-04-28T11:00:00",
      "client_id":2,
      "client_id": 2,
      "activity": "Circle Time",
      "interval_rating": 4,
      "client_id": 1,
      "interval_notes": "Participated well in circle time, minimal redirection needed"
    },

      
    {
      "id": 31,
      "start_interval": "2024-04-28T08:00:00",
      "end_interval": "2024-04-28T08:15:00",
      "client_id":3,
      "client_id": 3,
      "activity": "Math",
      "interval_tags": {"Non-Compliance": 5},
      "interval_rating": 2,
      "client_id": 1,
      "interval_notes": "Refused to engage in math activity"
    },
    {
      "id": 32,
      "start_interval": "2024-04-28T08:15:00",
      "end_interval": "2024-04-28T08:30:00",
      "client_id":3,
      "client_id": 3,
      "activity": "Recess",
      "interval_tags": {"Aggression": 3},
      "interval_rating": 3,
      "client_id": 1,
      "interval_notes": "Engaged in aggressive behavior towards peers"
    },
    {
      "id": 33,
      "start_interval": "2024-04-28T08:30:00",
      "end_interval": "2024-04-28T08:45:00",
      "client_id":3,
      "client_id": 3,
      "activity": "Art",
      "interval_tags": {"Property Destruction": 4},
      "interval_rating": 1,
      "client_id": 1,
      "interval_notes": "Destroyed art supplies during activity"
    },
    {
      "id": 34,
      "start_interval": "2024-04-28T08:45:00",
      "end_interval": "2024-04-28T09:00:00",
      "client_id":3,
      "client_id": 3,
      "activity": "Circle Time",
      "interval_tags": {"Non-Compliance": 3},
      "interval_rating": 1,
      "client_id": 1,
      "interval_notes": "Refused to participate in circle time"
    },
    {
      "id": 35,
      "start_interval": "2024-04-28T09:00:00",
      "end_interval": "2024-04-28T09:15:00",
      "client_id":3,
      "client_id": 3,
      "activity": "Lunch",
      "interval_tags": {"Food Refusal": 5},
      "interval_rating": 1,
      "client_id": 1,
      "interval_notes": "Refused to eat lunch, seeking attention"
    },
    {
      "id": 36,
      "start_interval": "2024-04-28T09:15:00",
      "end_interval": "2024-04-28T09:30:00",
      "client_id":3,
      "client_id": 3,
      "activity": "P.E.",
      "interval_tags": {"Elopement": 4},
      "interval_rating": 1,
      "client_id": 1,
      "interval_notes": "Attempted to leave gymnasium during physical education"
    },
    {
      "id": 37,
      "start_interval": "2024-04-28T09:30:00",
      "end_interval": "2024-04-28T09:45:00",
      "client_id":3,
      "client_id": 3,
      "activity": "Science",
      "interval_tags": {"Task Refusal": 4},
      "interval_rating": 3,
      "client_id": 1,
      "interval_notes": "Refused to participate in science experiment, seeking escape"
    },
    {
      "id": 38,
      "start_interval": "2024-04-28T09:45:00",
      "end_interval": "2024-04-28T10:00:00",
      "client_id":3,
      "client_id": 3,
      "activity": "Art",
      "interval_tags": {"Non-Compliance": 5},
      "interval_rating": 1,
      "client_id": 1,
      "interval_notes": "Ignored teacher's instructions during art activity"
    },
    {
      "id": 39,
      "start_interval": "2024-04-28T10:00:00",
      "end_interval": "2024-04-28T10:15:00",
      "client_id":3,
      "client_id": 3,
      "activity": "Snack",
      "interval_tags": {"Task Refusal": 3},
      "interval_rating": 3,
      "client_id": 1,
      "interval_notes": "Refused snack, seeking escape from activity"
    },
    {
      "id": 40,
      "start_interval": "2024-04-28T10:15:00",
      "end_interval": "2024-04-28T10:30:00",
      "client_id":3,
      "client_id": 3,
      "activity": "Reading",
      "interval_tags": {"Inattention": 4},
      "interval_rating": 2,
      "client_id": 1,
      "interval_notes": "Distracted during reading, seeking attention"
    },
    {
      "id": 41,
      "start_interval": "2024-04-28T10:30:00",
      "end_interval": "2024-04-28T10:45:00",
      "client_id":3,
      "client_id": 3,
      "activity": "Math",
      "interval_tags": {"Non-Compliance": 3},
      "interval_rating": 3,
      "client_id": 1,
      "interval_notes": "Refused to engage in math activity, seeking escape"
    },
    {
      "id": 42,
      "start_interval": "2024-04-28T10:45:00",
      "end_interval": "2024-04-28T11:00:00",
      "client_id":3,
      "client_id": 3,
      "activity": "Circle Time",
      "interval_tags": {"Aggression": 4},
      "interval_rating": 1,
      "client_id": 1,
      "interval_notes": "Engaged in aggressive behavior towards classmates"
    }
]